…

diff --git a/bash/bash_aliases b/bash/bash_aliases
--- a/bash/bash_aliases
+++ b/bash/bash_aliases
@@ -52,6 +52,35 @@ if command -v pass &>/dev/null; then
     alias pg='pass generate -c -i'
     alias pi='pass insert -m'
     alias po='pass otp -c'
+
+    pu() {
+        if [ "$#" -ne 1 ]; then
+            echo "Usage: pu <entry>" >&2
+            return 1
+        fi
+
+        entry="$1"
+
+        username=$(pass show "$entry" | awk -F': *' '/^\s*username:/ {print $2}' | xargs)
+        if [ -n "$username" ]; then
+            clip_time="${PASSWORD_STORE_CLIP_TIME:-45}"
+            old_clip=$(wl-paste)
+
+            printf "%s" "$username" | wl-copy
+
+            (
+                sleep "$clip_time"
+                current_clip=$(wl-paste)
+                if [ "$current_clip" = "$username" ]; then
+                    printf "%s" "$old_clip" | wl-copy
+                fi
+            ) &
+            echo "Username copied to clipboard. Will clear in $clip_time seconds."
+        else
+            echo "Error: Username not found for '$entry'."
+            return 1
+        fi
+    }
 fi
 
 # abbr in fish
