…

diff --git a/bash/bash_aliases b/bash/bash_aliases
--- a/bash/bash_aliases
+++ b/bash/bash_aliases
@@ -7,10 +7,12 @@
 
 # ls options
 #   -A, --almost-all: do not list implied . and ..
-alias l='ls -l'
+alias l='ls'
+alias ll='ls -l'
 alias la='ls -lA'
 alias lad='ls -ld'
 alias laa='ls -la'
+alias lag='ls -lA --group-directories-first'
 alias laz='ls -laZ'
 alias ladz='ls -ladZ'
 alias lazd='ls -ladZ'
@@ -50,20 +52,23 @@ if command -v pass &>/dev/null; then
     alias pi='pass insert -m'
 fi
 
-# .
+# abbr in fish
 alias c='cat'
 alias f='fd'
 alias r='rg'
 alias g='rg'
-alias t='tree -D'
+alias t='tree'
 alias v='vim'
+alias vo='NVIM_APPNAME=nvim-prev vim' # old
+alias vn='NVIM_APPNAME=nvim-test vim' # new
+alias sshk="ssh -F /dev/null -o IdentitiesOnly=yes -i ~/.ssh/"
 
 # tmux
 # https://github.com/lewisacidic/fish-tmux-abbr
-alias s='tmux attach || tmux new-session -s $TMUX_DEFAULT_SESSION_NAME'
-alias ss='tmux new-session -A -s'
-alias sx='tmux kill-session -t'
-alias sl='tmux list-sessions'
+# alias s='tmux attach || tmux new-session -s $TMUX_DEFAULT_SESSION_NAME'
+# alias ss='tmux new-session -A -s'
+# alias sx='tmux kill-session -t'
+# alias sl='tmux list-sessions'
 
 # git
 # https://github.com/lewisacidic/fish-git-abbr
@@ -75,31 +80,51 @@ alias gco='git checkout'
 alias gd='git diff'
 alias gf='git fetch'
 alias gl='git log'
+alias gls='git log --show-signature'
 alias gp='git push'
 alias gpl='git pull'
 alias gr='git remote -v'
+alias grl='git reflog'
 alias grs='git reset'
-alias grs!='git reset --hard'
+alias grs!='git reset --hard' # grs!
 alias gs='git status'
+if command -v gitleaks &>/dev/null; then
+    alias glp='gitleaks git --verbose --pre-commit --staged'
+fi
 if command -v lazygit &>/dev/null; then
     alias lg='lazygit'
 fi
 
 if command -v bat &>/dev/null; then
     bat_cmd='bat'
-    alias bat='bat -pp'
-    alias c='bat -pp'
+    # alias cat='bat -pp' # no paging
+    alias cat='bat -p'
     alias d='batdiff'
+    alias bd='batdiff'
 fi
 
 if command -v batcat &>/dev/null; then
     bat_cmd='batcat'
-    alias bat='batcat -pp'
-    alias c='batcat -pp'
+    alias bat='batcat'
+    # alias cat='batcat -pp' # no paging
+    alias cat='batcat -p'
     alias d='batdiff'
+    alias bd='batdiff'
+fi
+
+if command -v difft &>/dev/null; then
+    alias d='difftastic'
 fi
 
 alias n='npm'
+alias nx='npx'
+
+if command -v pnpm &>/dev/null; then
+    alias npm='pnpm'
+    alias npx='pnpx'
+    alias n='pnpm'
+    alias nx='pnpx'
+fi
 
 ##
 ## Functions
@@ -114,6 +139,17 @@ if [[ $bat_cmd ]]; then
         fi
 
         git diff --name-only --relative --diff-filter=d "$@" | xargs "$bat_cmd" --diff
+    }
+fi
+
+if commnd -v difft &>/dev/null; then
+    difftastic() {
+        if ! is_git_repo; then
+            echo 'Error: Unable to locate a Git repository.'
+            return 1
+        fi
+
+        git -c diff.external=difft diff
     }
 fi
 
@@ -159,11 +195,11 @@ gg() {
     use_ai=0
 
     if [ $# -eq 0 ]; then
-        if command -v aicommits &>/dev/null; then
+        if command -v aicommit &>/dev/null; then
             use_ai=1
         else
             echo "Usage: gg [commit message]"
-            echo "Info: aicommits not present"
+            echo "Info: Didn't find aicommit"
             return 1
         fi
     fi
@@ -172,7 +208,7 @@ gg() {
         # using aicomments
         # echo statements has bold text
         echo -e "\e[1mgit add -A\e[0m" && git add -A &&
-            echo -e "\e[1maicommits\e[0m" && aicommits &&
+            echo -e "\e[1maicommit\e[0m" && aicommit &&
             echo -e "\e[1mgit push\e[0m" && git push
     else
         # using user supplied commit message
@@ -182,6 +218,82 @@ gg() {
             echo -e "\e[1mgit push\e[0m" && git push
     fi
 }
+
+aicommit() {
+    if ! is_git_repo; then
+        echo 'Error: Unable to locate a Git repository.'
+        return 1
+    fi
+
+    if ! command -v openai &>/dev/null; then
+        echo "Error: 'openai' not found."
+        return 1
+    fi
+
+    if git diff --cached --quiet; then
+        echo "No staged changes found."
+        return 1
+    fi
+
+    local continue='n'
+    while [ "$continue" != "y" ] && [ "$continue" != "Y" ]; do
+        local message
+        message=$(openai api chat.completions.create \
+            -m gpt-4 \
+            -g user "Write a concise commit message for the following git diff:" \
+            -g user "$(git diff --cached)")
+
+        # shellcheck disable=SC2181 # Check exit code directly with e.g. 'if ! mycmd;', not indirectly with $?
+        if [ $? -ne 0 ]; then
+            echo "Error: Couldn't retrieve a commit message from 'openai'"
+            return 1
+        fi
+
+        echo
+        echo "$message"
+        read -r -p "Use this commit message? [y/N/q]: " continue
+        if [ "$continue" = "q" ]; then
+            return 0
+        fi
+    done
+
+    git commit -m "$message"
+}
+
+# gg (git add, git commit, git push)
+# usage: gg [commit message]
+# gg() {
+#     if ! is_git_repo; then
+#         echo 'Error: Unable to locate a Git repository.'
+#         return 1
+#     fi
+#
+#     use_ai=0
+#
+#     if [ $# -eq 0 ]; then
+#         if command -v aicommits &>/dev/null; then
+#             use_ai=1
+#         else
+#             echo "Usage: gg [commit message]"
+#             echo "Info: aicommits not present"
+#             return 1
+#         fi
+#     fi
+#
+#     if [ $use_ai -eq 1 ]; then
+#         # using aicomments
+#         # echo statements has bold text
+#         echo -e "\e[1mgit add -A\e[0m" && git add -A &&
+#             echo -e "\e[1maicommits\e[0m" && aicommits &&
+#             echo -e "\e[1mgit push\e[0m" && git push
+#     else
+#         # using user supplied commit message
+#         # echo statements has bold text
+#         echo -e "\e[1mgit add -A\e[0m" && git add -A &&
+#             echo -e "\e[1mgit commit -m \"$1\"\e[0m" && git commit -m "$1" &&
+#             echo -e "\e[1mgit push\e[0m" && git push
+#     fi
+# }
 
 # ww (git add, git commit, git push - whatthecommit.com)
 # usage: ww
@@ -264,14 +376,22 @@ git-tidy() {
         return 1
     fi
 
-    if ! git clone --mirror . "$backup_dir"; then
+    local git_dir
+    if ! git_dir=$(git rev-parse --show-toplevel); then
+        echo "Error: Unable to locate Git root directory"
+        rm -rf "$backup_dir"
+        return 1
+    fi
+    echo "Info: Git root directory: $git_dir"
+
+    if ! git clone --mirror "$git_dir" "$backup_dir"; then
         echo "Error: Couldn't create backup"
         rm -rf "$backup_dir"
         return 1
     fi
 
     # Commit message
-    commit_message="Git History Cleanup"
+    commit_message="…"
     if [ $# -gt 0 ]; then
         commit_message=$*
     fi
@@ -361,11 +481,9 @@ else
     source /etc/os-release
     case $ID in
     'fedora')
-        [[ -n $BASH_VERSION ]] && export -f upd_fedora
         alias upd='upd_fedora'
         ;;
     'ubuntu')
-        [[ -n $BASH_VERSION ]] && export -f upd_ubuntu
         alias upd='upd_ubuntu'
         ;;
     *)
@@ -384,24 +502,68 @@ upd_gh_extensions() {
 }
 
 upd_npm() {
-    if command -v /usr/local/bin/npm &>/dev/null; then
+    if command -v fnm &>/dev/null; then
+        if command -v pnpm &>/dev/null; then
+            echo -e '\e[1mUpdating npm -- user\e[0m'
+            echo -e '\e[3mfnm, pnpm self-update, pnpm install -g npm@latest\e[0m'
+            fnm use lts 1>/dev/null
+            pnpm self-update 1>/dev/null
+            pnpm install -g npm@latest 1>/dev/null
+            echo "node: $(fnm current) (lts)"
+            echo "pnpm: $(pnpm --version)"
+            echo
+            fnm use latest 1>/dev/null
+            pnpm self-update 1>/dev/null
+            pnpm install -g npm@latest 1>/dev/null
+            echo "node: $(fnm current) (latest)"
+            echo "pnpm: $(pnpm --version)"
+            echo
+        else
+            echo -e '\e[1mUpdating npm -- user\e[0m'
+            echo -e '\e[3mfnm, npm install -g npm@latest\e[0m\n'
+            fnm use lts 1>/dev/null
+            npm install -g npm@latest 1>/dev/null
+            echo "node: $(fnm current) (lts)"
+            echo "npm: $(npm --version)"
+            echo
+            fnm use latest 1>/dev/null
+            npm install -g npm@latest 1>/dev/null
+            echo "node: $(fnm current) (latest)"
+            echo "npm: $(npm --version)"
+            echo
+        fi
+    fi
+
+    if ! command -v fnm &>/dev/null && command -v /usr/local/bin/npm &>/dev/null; then
         echo -e '\e[1mUpdating npm\e[0m'
         echo -e '\e[3msudo npm install -g npm@latest\e[0m'
         sudo /usr/local/bin/npm install -g npm@latest
         echo
-        echo "NPM version: $(/usr/local/bin/npm --version)"
+        echo "node: $(node --version)"
+        echo "npm: $(/usr/local/bin/npm --version)"
         echo
     fi
 }
 
-upd_npm_packages() {
-    if command -v /usr/local/bin/npm &>/dev/null; then
-        echo -e '\e[1mUpdating npm packages\e[0m'
-        echo -e '\e[3msudo npm packages\e[0m'
-        sudo /usr/local/bin/npm update
-        echo
-    fi
-}
+# upd_npm() {
+#     if command -v /usr/local/bin/npm &>/dev/null; then
+#         echo -e '\e[1mUpdating npm\e[0m'
+#         echo -e '\e[3msudo npm install -g npm@latest\e[0m'
+#         sudo /usr/local/bin/npm install -g npm@latest
+#         echo
+#         echo "NPM version: $(/usr/local/bin/npm --version)"
+#         echo
+#     fi
+# }
+#
+# upd_npm_packages() {
+#     if command -v /usr/local/bin/npm &>/dev/null; then
+#         echo -e '\e[1mUpdating npm packages\e[0m'
+#         echo -e '\e[3msudo npm packages\e[0m'
+#         sudo /usr/local/bin/npm update
+#         echo
+#     fi
+# }
 
 upd_go() {
     # example download url: https://go.dev/dl/go1.22.3.linux-amd64.tar.gz
@@ -534,6 +696,88 @@ upd_go() {
         echo
         echo "Go version: $(/usr/local/go/bin/go version | awk '{print $3}')"
         echo
+    fi
+}
+
+init_shell_completion_bash() {
+    mkdir -p "$XDG_CONFIG_HOME/bash/completions"
+
+    # bat
+    if command -v bat &>/dev/null; then
+        bat --completion bash >"$XDG_CONFIG_HOME/bash/completions/bat.bash"
+    fi
+
+    # batcat
+    if command -v batcat &>/dev/null; then
+        batcat --completion bash >"$XDG_CONFIG_HOME/bash/completions/batcat.bash"
+    fi
+
+    # fnm
+    if command -v fnm &>/dev/null; then
+        fnm completions --shell bash >"$XDG_CONFIG_HOME/bash/completions/fnm.bash"
+    fi
+
+    # fzf
+    if command -v fzf &>/dev/null; then
+        # https://github.com/junegunn/fzf#setting-up-shell-integration
+        # https://github.com/junegunn/fzf#key-bindings-for-command-line
+        fzf --bash >"$XDG_CONFIG_HOME/bash/completions/fzf.bash"
+    fi
+
+    # github cli
+    if command -v gh &>/dev/null; then
+        gh completion -s bash >"$XDG_CONFIG_HOME/bash/completions/gh.bash"
+    fi
+
+    # gitleaks
+    if command -v gitleaks &>/dev/null; then
+        gitleaks completion bash >"$XDG_CONFIG_HOME/bash/completions/gitleaks.bash"
+    fi
+
+    # wezterm
+    if command -v wezterm &>/dev/null; then
+        wezterm shell-completion --shell bash >"$XDG_CONFIG_HOME/bash/completions/wezterm.bash"
+    fi
+}
+
+init_shell_completion_zsh() {
+    mkdir -p "$XDG_CONFIG_HOME/zsh/completions"
+
+    # bat
+    if command -v bat &>/dev/null; then
+        bat --completion zsh >"$XDG_CONFIG_HOME/zsh/completions/bat.zsh"
+    fi
+
+    # batcat
+    if command -v batcat &>/dev/null; then
+        batcat --completion zsh >"$XDG_CONFIG_HOME/zsh/completions/batcat.zsh"
+    fi
+
+    # fnm
+    if command -v fnm &>/dev/null; then
+        fnm completions --shell zsh >"$XDG_CONFIG_HOME/zsh/completions/fnm.zsh"
+    fi
+
+    # fzf
+    if command -v fzf &>/dev/null; then
+        # https://github.com/junegunn/fzf#setting-up-shell-integration
+        # https://github.com/junegunn/fzf#key-bindings-for-command-line
+        fzf --zsh >"$XDG_CONFIG_HOME/zsh/completions/fzf.zsh"
+    fi
+
+    # github cli
+    if command -v gh &>/dev/null; then
+        gh completion -s zsh >"$XDG_CONFIG_HOME/zsh/completions/gh.zsh"
+    fi
+
+    # gitleaks
+    if command -v gitleaks &>/dev/null; then
+        gitleaks completion zsh >"$XDG_CONFIG_HOME/zsh/completions/gitleaks.zsh"
+    fi
+
+    # wezterm
+    if command -v wezterm &>/dev/null; then
+        wezterm shell-completion --shell zsh >"$XDG_CONFIG_HOME/zsh/completions/wezterm.zsh"
     fi
 }
 
